apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-dist-mnist-mpi"
  namespace: "hxz-cabt"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: kubeflow/pytorch-dist-mnist:latest
              imagePullPolicy: IfNotPresent   ### 新增
              args: ["--backend", "mpi"]
              # Comment out the below resources to use the CPU.
              # resources:
              #   limits:
              #     nvidia.com/gpu: 1
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          initContainers:
            - name: init-pytorch
              image: kmu1/kubectl-delivery:latest
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: 100m
                  memory: 20Mi
                requests:
                  cpu: 50m
                  memory: 10Mi
              command: ['sh', '-c', 'err=1;for i in $(seq 100); do if nslookup master; then err=0 && break; fi; echo waiting for master; sleep 2; done; exit $err']
          containers:
            - name: pytorch
              image: kubeflow/pytorch-dist-mnist:latest
              imagePullPolicy: IfNotPresent   ### 新增
              args: ["--backend", "mpi"]
              # Comment out the below resources to use the CPU.
              # resources:
              #   limits:
              #     nvidia.com/gpu: 1
