apiVersion: batch/v1
kind: Job
metadata:
  name: training-operator
  labels:
    app: training-operator
  namespace: hxz-cabt
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: training-operator
    spec:
      serviceAccountName: training-operator ##
      restartPolicy: OnFailure
      containers:
      - name: gencerts
        image: kmu1/training-operator-gencerts:latest
        imagePullPolicy: IfNotPresent
        command: ["/usr/bin/gencerts.sh","-p","-n","hxz-cabt"]


