# kustomization.yaml 的内容已被注释，因为我们不使用 kustomize
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
#   - manifests.yaml
# commonLabels:
#   control-plane: kubeflow-training-operator
# patches:
#   - path: patch.yaml
#     target:
#       group: admissionregistration.k8s.io
#       version: v1
#       kind: ValidatingWebhookConfiguration
# configurations:
#   - kustomizeconfig.yaml

# ---
# kustomizeconfig.yaml 的内容，如果不使用 kustomize，此部分可以忽略
# namespace:
#   - kind: ValidatingWebhookConfiguration
#     group: admissionregistration.k8s.io
#     path: webhooks/clientConfig/service/namespace
#     create: true
# varReference:
#   - path: metadata/annotations

---
# manifests.yaml 的内容
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: training-operator
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: training-operator
      namespace: system
      path: /validate-kubeflow-org-v1-mxjob
  failurePolicy: Fail
  name: validator.mxjob.training-operator.kubeflow.org
  rules:
  - apiGroups:
    - kubeflow.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - mxjobs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: training-operator
      namespace: system
      path: /validate-kubeflow-org-v1-paddlejob
  failurePolicy: Fail
  name: validator.paddlejob.training-operator.kubeflow.org
  rules:
  - apiGroups:
    - kubeflow.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - paddlejobs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: training-operator
      namespace: system
      path: /validate-kubeflow-org-v1-pytorchjob
  failurePolicy: Fail
  name: validator.pytorchjob.training-operator.kubeflow.org
  rules:
  - apiGroups:
    - kubeflow.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pytorchjobs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: training-operator
      namespace: system
      path: /validate-kubeflow-org-v1-tfjob
  failurePolicy: Fail
  name: validator.tfjob.training-operator.kubeflow.org
  rules:
  - apiGroups:
    - kubeflow.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tfjobs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: training-operator
      namespace: system
      path: /validate-kubeflow-org-v1-xgboostjob
  failurePolicy: Fail
  name: validator.xgboostjob.training-operator.kubeflow.org
  rules:
  - apiGroups:
    - kubeflow.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - xgboostjobs
  sideEffects: None

# ---
# patch.yaml 的内容，如果不使用 kustomize，此部分可以直接应用到 manifests.yaml 中
# - op: replace
#   path: /webhooks/0/clientConfig/service/name
#   value: mpioperator-webhook-service
# 其他框架的 patch 操作已被注释
# - op: replace
#   path: /webhooks/1/clientConfig/service/name
#   value: training-operator
# - op: replace
#   path: /webhooks/2/clientConfig/service/name
#   value: training-operator
# - op: replace
#   path: /webhooks/3/clientConfig/service/name
#   value: training-operator
# - op: replace
#   path: /webhooks/4/clientConfig/service/name
#   value: training-operator
# - op: replace
#   path: /metadata/name
#   value: validator.training-operator.kubeflow.org